//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cvPageWeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class resupEntities1 : DbContext
    {
        public resupEntities1()
            : base("name=resupEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_HOBBY> TBL_HOBBY { get; set; }
        public virtual DbSet<TBL_RESET_PASS_REQUEST> TBL_RESET_PASS_REQUEST { get; set; }
        public virtual DbSet<TBL_MEMBER_ROLES> TBL_MEMBER_ROLES { get; set; }
        public virtual DbSet<TBL_CERTIFICATE> TBL_CERTIFICATE { get; set; }
        public virtual DbSet<TBL_REFERENCE> TBL_REFERENCE { get; set; }
        public virtual DbSet<TBL_PROJECTS> TBL_PROJECTS { get; set; }
        public virtual DbSet<TBL_ABILITY> TBL_ABILITY { get; set; }
        public virtual DbSet<TBL_LANG> TBL_LANG { get; set; }
        public virtual DbSet<TBL_EDUCATION> TBL_EDUCATION { get; set; }
        public virtual DbSet<TBL_SINGULAR_INFO> TBL_SINGULAR_INFO { get; set; }
        public virtual DbSet<TBL_EXPERIENCE> TBL_EXPERIENCE { get; set; }
        public virtual DbSet<TBL_WORK_TYPE_LIST> TBL_WORK_TYPE_LIST { get; set; }
        public virtual DbSet<TBL_MEMBERS> TBL_MEMBERS { get; set; }
        public virtual DbSet<TBL_GUEST_MESSAGES> TBL_GUEST_MESSAGES { get; set; }
        public virtual DbSet<TBL_CITY_LIST> TBL_CITY_LIST { get; set; }
    }
}
