//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cvPageWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LANG
    {
        public int id { get; set; }
        public Nullable<int> placement { get; set; }
        public string lang { get; set; }
        public string point_source { get; set; }
        public string point { get; set; }
        public string point_full { get; set; }
        public string reading_point { get; set; }
        public string reading_point_full { get; set; }
        public string writing_point { get; set; }
        public string writing_point_full { get; set; }
        public string speaking_point { get; set; }
        public string speaking_point_full { get; set; }
        public Nullable<int> lang_level { get; set; }
        public Nullable<int> member_id { get; set; }
        public string visible { get; set; }
        public string source_visible { get; set; }
        public string point_visible { get; set; }
        public string rws_visible { get; set; }
    }
}
