//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cvPageWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXPERIENCE
    {
        public int id { get; set; }
        public Nullable<int> placement { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public string company_name { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string city { get; set; }
        public string work_type { get; set; }
        public Nullable<int> member_id { get; set; }
        public string visible { get; set; }
    }
}
