//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cvPageWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SINGULAR_INFO
    {
        public int id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string profile_photo { get; set; }
        public string photo_visible { get; set; }
        public string job { get; set; }
        public string tel_visible { get; set; }
        public string tel { get; set; }
        public string linkedin { get; set; }
        public string location { get; set; }
        public string summary { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> birt_date { get; set; }
        public string gender_visible { get; set; }
        public string gender { get; set; }
        public string nation_visible { get; set; }
        public string nationality { get; set; }
        public string drive_licence { get; set; }
        public string summary_head { get; set; }
        public string contact_head { get; set; }
        public string education_head { get; set; }
        public string lang_head { get; set; }
        public string experience_head { get; set; }
        public string projects_head { get; set; }
        public string certification_head { get; set; }
        public string areas_of_exp_head { get; set; }
        public string reference_head { get; set; }
        public string personel_info_head { get; set; }
        public string summary_visible { get; set; }
        public string contact_visible { get; set; }
        public string education_visible { get; set; }
        public string lang_visible { get; set; }
        public string experience_visible { get; set; }
        public string projects_visible { get; set; }
        public string certification_visible { get; set; }
        public string areas_of_expertise_visible { get; set; }
        public string reference_visible { get; set; }
        public string personel_info_visible { get; set; }
        public string military_situation { get; set; }
        public Nullable<System.DateTime> military_date { get; set; }
        public string mlitary_visible { get; set; }
    }
}
