//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cvPageWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EDUCATION
    {
        public int id { get; set; }
        public Nullable<int> placement { get; set; }
        public Nullable<System.DateTime> education_start_date { get; set; }
        public Nullable<System.DateTime> education_finish_date { get; set; }
        public string department { get; set; }
        public string gpa { get; set; }
        public string gpa_full { get; set; }
        public string school { get; set; }
        public string lang { get; set; }
        public Nullable<int> member_id { get; set; }
        public string visible { get; set; }
        public string gpa_visible { get; set; }
    }
}
